source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
limit_posts: 0

relative_permalinks: true

permalink:     /:month-:day-:year/:title.html

baseurl:     /
pygments:    true
markdown:    "redcarpet"

name: Maptime
description: Time to hack...on maps!
url: http://www.maptime.io